name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Trigger APP CI Build
        run: |
          curl 'https://api.github.com/repos/Yuameshi/PhiCommunityAPP/dispatches' --request POST \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --data-raw '{"event_type": "CI Build triggered by Repo:PhiCommunity"}'